//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaHCM.QA.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_BBS
    {
        public int BBSId { get; set; }
        public int TopicId { get; set; }
        public int BoardId { get; set; }
        public string Content { get; set; }
        public int PostUserId { get; set; }
        public string PostUserName { get; set; }
        public System.DateTime PostTime { get; set; }
        public string PostIp { get; set; }
        public int IsTopic { get; set; }
        public int IsAnswer { get; set; }
        public int DisplayMode { get; set; }
        public int AnswerMode { get; set; }
        public int Status { get; set; }
    
        public virtual e_Topic e_Topic { get; set; }
        public virtual e_Users e_Users { get; set; }
    }
}
