//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaHCM.QA.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_Board
    {
        public e_Board()
        {
            this.e_Topic = new HashSet<e_Topic>();
        }
    
        public int BoardId { get; set; }
        public string Name { get; set; }
        public int Depth { get; set; }
        public int ParentID { get; set; }
        public int RootID { get; set; }
        public int Order { get; set; }
        public int IsLeaf { get; set; }
        public int IsPublic { get; set; }
        public int BoardType { get; set; }
        public string Master { get; set; }
        public System.DateTime AddTime { get; set; }
        public int TopicNum { get; set; }
        public int PostNum { get; set; }
        public string ParentStr { get; set; }
    
        public virtual ICollection<e_Topic> e_Topic { get; set; }
    }
}
