//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinaHCM.QA.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_Topic
    {
        public e_Topic()
        {
            this.e_BBS = new HashSet<e_BBS>();
        }
    
        public int TopicId { get; set; }
        public int BoardId { get; set; }
        public int TopicType { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public int PostUserId { get; set; }
        public string PostUserName { get; set; }
        public System.DateTime PostTime { get; set; }
        public string PostIp { get; set; }
        public Nullable<int> LastPostUserId { get; set; }
        public string LastPostUserName { get; set; }
        public Nullable<System.DateTime> LastPostTime { get; set; }
        public int Status { get; set; }
        public int IsFinish { get; set; }
        public int IsLock { get; set; }
        public int IsDigest { get; set; }
        public int TopLevel { get; set; }
        public int Child { get; set; }
        public int Hits { get; set; }
    
        public virtual ICollection<e_BBS> e_BBS { get; set; }
        public virtual e_Board e_Board { get; set; }
        public virtual e_Users e_Users { get; set; }
    }
}
